export const GET_ALL_DOGS = 'GET_ALL_DOGS'
export const GET_NAME_DOG = 'GET_NAME_DOG'
export const GET_TEMPERAMENTS= 'GET_TEMPERAMENTS'
export const FILTER_BY_TEMPERAMENTS = 'FILTER_BY_TEMPERAMENTS'
export const FILTER_CREATED = 'FILTER_CREATED'
export const ORDER_BY_NAME = 'ORDER_BY_NAME'
export const POST_DOG = 'POST_DOG'
export const DETAIL_DOG = 'DETAIL_DOG'


// GET_ALL_DOG
// GET_NAME_DOG
// GET_TEMPERAMENTS
// FILTER_BY_TEMPERAMENTS
// FILTER_CREATED
// ORDER_BY_NAME
// POST_DOG
// POST_DOG
// DETAIL_DOG